### ISSUE TITLE
Add % unattached to the unattached volumes report

### ISSUE THREAD

**Issue by ryanoleary** [flexera-public/policy_templates#192]
### Policy Template Name
Unattached Volumes

### Issue Type
Feature Request

### Use Case (Feature Request -or- New Policy Template Request Only)
Customer would like to see the "% unattached" as part of this report so that they know how much of their storage landscape is impacted. They currently get this information from Account Overview in CM but would rather have it part of the report.

**Comment by srpomeroy** [comment]
@ryanoleary % of number of volumes or percent of total storage capacity?
Assuming % of number of volumes, but figured it was important to clarify because one 4 TB volume potentially costs more than one hundred 10 GB volumes.
