### ISSUE TITLE
AWS Rightsize EBS Volumes Policy Throttling

### ISSUE THREAD

**Issue by Fumigatus** [flexera-public/policy_templates#2812]
### Policy Template Name
AWS Rightsize EBS Volumes

### Issue Type
Throttling when interacting with AWS API

### Use Case (Feature Request -or- New Policy Template Request Only)
When I used to AWS Rightsize EBS Volumes template policy without any changes (just removed cloudflow section). There is an issue accord. HTTP code 400 Bad Request with message 
```
{"__type":"com.amazon.coral.availability#ThrottlingException","message":"Request has been throttled."}
```

### Policy Template version (Bug Only)
```rs_pt_ver 20180301```
```
info(
  version: "0.3.2",
  provider: "AWS",
  service: "EBS",
  policy_set: "Unused Volumes",
  recommendation_type: "Usage Reduction",
  hide_skip_approvals: "true"
)
```

### Code Snippet (Bug Only)
```ruby
datasource "ds_cloudwatch_getmetricdata_iops_utilization" do
  iterate $ds_metricdataqueries_iops_utilization
  request do
    run_script $js_cloudwatch_getmetricdata_iops_utilization, val(iter_item, "region"), val(iter_item, "MetricDataQueries"), $param_unused_days
  end
  result do
    encoding "json"
    collect jmes_path(response, "MetricDataResults[*]") do
      field "region", val(iter_item, "region")
      field "id", jmes_path(col_item, "Id")
      field "label", jmes_path(col_item, "Label")
      field "values", jmes_path(col_item, "Values")
    end
  end
end

script "js_cloudwatch_getmetricdata_iops_utilization", type: "javascript" do
  parameters "region", "MetricDataQueries", "param_unused_days"
  result "request"
  code <<-EOS
  // Slow down rate of requests to prevent throttling
  api_wait = 5
  var now = new Date().getTime()
  while(new Date().getTime() < now + (api_wait * 1000)) { /* Do nothing */ }

  end_date = parseInt(new Date().getTime() / 1000)
  start_date = parseInt(new Date(new Date().setDate(new Date().getDate() - param_unused_days)).getTime() / 1000)

  var request = {
    auth: "auth_aws",
    host: "monitoring." + region + ".amazonaws.com",
    verb: "POST",
    path: "/",
    pagination: "pagination_aws_getmetricdata",
    headers: {
      "User-Agent": "RS Policies",
      "Content-Type": "application/json",
      "x-amz-target": "GraniteServiceVersion20100801.GetMetricData",
      "Accept": "application/json",
      "Content-Encoding": "amz-1.0"
    }
    query_params: {
      "Action": "GetMetricData",
      "Version": "2010-08-01"
    },
    body: JSON.stringify({
      "StartTime": start_date,
      "EndTime": end_date,
      "MetricDataQueries": MetricDataQueries
    })
  }
EOS
end
```

### Error Messages (Bug Only)
```
Evaluation failed to complete with the following errors:
Summary:
  failed to retrieve datasource data
Detail:
  unexpected response status
  POST https://monitoring.eu-west-3.amazonaws.com/?Action=GetMetricData&Version=2010-08-01
  got "400 Bad Request", expected a status in the 200 range
  response body:
  {"__type":"com.amazon.coral.availability#ThrottlingException","message":"Request has been throttled."}
Location:
  datasource "ds_idle_volumes_result"
    script "js_idle_volumes_result"
      argument "ds_volume_cost_mapping"
        datasource "ds_volume_cost_mapping"
          script "js_volume_cost_mapping"
            argument "ds_idle_volumes"
              datasource "ds_idle_volumes"
                script "js_idle_volumes"
                  argument "ds_cloudwatch_getmetricdata_iops_utilization"
                    datasource "ds_cloudwatch_getmetricdata_iops_utilization"

Summary:
  failed to retrieve datasource data
Detail:
  unexpected response status
  POST https://monitoring.eu-west-3.amazonaws.com/?Action=GetMetricData&Version=2010-08-01
  got "400 Bad Request", expected a status in the 200 range
  response body:
  {"__type":"com.amazon.coral.availability#ThrottlingException","message":"Request has been throttled."}
Location:
  datasource "ds_underutilized_volumes_result"
    script "js_underutilized_volumes_result"
      argument "ds_volume_cost_mapping"
        datasource "ds_volume_cost_mapping"
          script "js_volume_cost_mapping"
            argument "ds_idle_volumes"
              datasource "ds_idle_volumes"
                script "js_idle_volumes"
                  argument "ds_cloudwatch_getmetricdata_iops_utilization"
                    datasource "ds_cloudwatch_getmetricdata_iops_utilization"
```

**Comment by XOmniverse** [comment]
Is this happening in a context where the AWS credential is only being used to execute this specific policy?

Normally this indicates that the user is hitting the AWS API elsewhere as well and, combined, this is hitting AWS's rate limit. This isn't something that can be fixed within the policy itself.

**Comment by Fumigatus** [comment]
Yes, I encountered this problem only in this policy.

Yes, we are stuck with the AWS API rate limit, but I tried a longer wait time for the api, like 20 seconds, and it still failed. 

For example, when I tried to change the chunk size above this code like 100, it didn't fail. But this time the policy takes too long. Because it does not return multiple page. 

I have some questions;

- Is there a way to add a delay to the pagination field?
- Is there a way to make it retry policy and error handling or exponential backoff for throttling when it gets an error?

![2bdbe336-af80-4bef-b724-0cdd6fdbf3a2](https://github.com/user-attachments/assets/b844e53e-a11f-4626-a29e-d2a3c8e39285)

**Comment by Fumigatus** [comment]
Yes, I encountered this problem only in this policy.

Yes, we are stuck with the AWS API rate limit, but I tried a longer wait time for the api, like 20 seconds, and it still failed.

For example, when I tried to change the chunk size above this code like 100, it didn't fail. But this time the policy takes too long. Because it does not return any page.

I have some questions;
- Can I add a delay to the pagination field?
- Is there a way to make it retry when it gets an error?

![d74c589c-a907-480f-92e5-650c6fae2f0f](https://github.com/user-attachments/assets/f2b73ec5-8fd5-435c-b777-252181513eef)

**Comment by Fumigatus** [comment]
Yes, I encountered this problem only in this policy.

Yes, we are stuck with the AWS API rate limit, but I tried a longer wait time for the api, like 20 seconds, and it still failed.

For example, when I tried to change the chunk size above this code like 100, it didn't fail. But this time the policy takes too long. Because it does not return any page.

I have some questions;

- Can I add a delay to the pagination field?
- Is there a way to make it retry and error handling or Exponential backoff when it gets an error?

![d74c589c-a907-480f-92e5-650c6fae2f0f](https://github.com/user-attachments/assets/845f5113-4a71-4ddb-87fb-e40f85b3a6e9)

**Comment by XOmniverse** [comment]
Currently, neither of these are supported. These would need to be changed within the policy engine itself on the Flexera side (and I believe we have open issues for both of those things, though I don't have any kind of ETA for delivery) rather than in the policy template.

There is a workaround you can do within policy templates that we usually avoid doing because it increases execution time, and policies have a 1 hour time limit for execution, so any added delays increase the risk of a policy timing out for users with large cloud estates. You can see an example here if you wanted to make your own customized templates that rely on this:

https://github.com/flexera-public/policy_templates/blob/85fd4d2a88327d058ffce235c7e5aa02acefae79/cost/aws/burstable_ec2_instances/aws_burstable_ec2_instances.pt#L537

That said, usually when this issue is happening, it means some other automation (either another policy template or automation outside of the Flexera platform) is hitting the same API and, combined, is causing the limit to be reached. I would recommend looking into that as well to make sure you're not experiencing issues due to this.

**Comment by Fumigatus** [comment]
I tried this before, I changed the api_wait value to 20 seconds or more as I mentioned above, but I was still getting throttling error. The only way was to reduce the chunk size. However, this was increasing the policy time too much.

Is there any other method I can try or follow?

**Comment by XOmniverse** [comment]
I can't think of anything else, apart from investigating where else you might be hitting the API concurrently with this policy template. If you're a Flexera user, I would recommend submitting a support ticket so that we can escalate things internally, because ultimately the fix for stuff like this (better handling of throttling errors for the policy engine, for example) will be with the underlying product/infrastructure itself rather than anything with the policy catalog.
