### ISSUE TITLE
Useful info in AWS Instance utilization.

### ISSUE THREAD

**Issue by kyleha-flexera** [flexera-public/policy_templates#497]
### Policy Template Name
AWS Instance CloudWatch Utilization

### Issue Type
Feature Request

### Use Case (Feature Request -or- New Policy Template Request Only)
What I have to identify instances on this report are instance IDs and IP addresses. (It says hostname and DNS name, but those are just IPs for me.) It would be useful to have the 'Name' and maybe 'env' tags. I might also like to know the instance type or just plain how much it cost.

In some cases I have reports for instances that no longer exist. That's still useful in case I want to adjust the conditions of their creation and destruction, but it makes it extra hard to figure out what something was after the fact. 

The reports I get have about a hundred instances in them. I don't know how you'd want to summarize that, but I'd love to have an alternative to going through it line by line.

**Comment by cdwilhelm** [comment]
Hi @kyleha-flexera   It looks like you may be using an old policy version of that policy.  Have you tried the **AWS Inefficient Instance Utilization using CloudWatch** policy yet.  It doesn't have the tags, but it has instance type.  AWS doesn't have names on the API output of instances,  but there is a name tag.  We can look into adding these changes.  I don't know about another way to present the data.  you can send your comments about new ways to visualize the data to dg-pm@flexera.com, which goes to the product manager.
