### ISSUE TITLE
The description on "Security Group High Open Ports Policy Template" template is not accurate

### ISSUE THREAD

**Issue by mastamark** [flexera-public/policy_templates#95]
### Policy Template Name
"Security Group High Open Ports Policy Template"

### Issue Type
Bug/Text Issue or perhaps feature request depending on how you want to play this

### Policy Template version (Bug Only)
Version: 1.3

### Code Snippet
The description of this policy template says:
``
short_description "A policy that sends email notifications when a security group has unapproved open ports. See the [README](https://github.com/rightscale/policy_templates/tree/master/security/security_groups/high_open_ports) and [docs.rightscale.com/policies](http://docs.rightscale.com/policies/) to learn more."
``

The actual policy however has no concept of "unapproved open ports" and instead just prompts for a value to check for public access to.  Eg, if you put 1000 for the param_port_info parameter, it will trigger for any open port above that.

Essentially the actual policy name is more accurate then the description, which seems to indicate to an end user that it would accept some sort of list of "unapproved open ports."

I would suggest this policy either be updated to support a csv list of "approved open ports" or at least update the description to remove the "unapproved open ports" part as its misleading.

**Comment by cdwilhelm** [comment]
@rshade this is the issue I mentioned about the open ports.  See the comments from the user.  maybe the logic needs to change or just update the description to better describe what it does.  thx
